
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
from PIL import Image, ImageTk

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from gui.gui2 import open_dashboard_page



def open_login_page():


    OUTPUT_PATH = Path(__file__).parent
    ASSETS_PATH = OUTPUT_PATH / Path(r"/Users/chrisalpuerto/Desktop/PROJECTS/AI Powered Intrution Detector CPSC 490 491/gui/assets/frame0")


    def relative_to_assets(path: str) -> Path:
        return ASSETS_PATH / Path(path)


    window = Tk()
    status_label = None

    window.geometry("713x446")
    window.configure(bg = "#FFFFFF")


    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 446,
        width = 713,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )
    status_label = canvas.create_text(
    265.0,
    300.0,
    anchor="nw",
    text="",
    fill="green",  # Will use green for success, red for failure
    font=("IstokWeb Regular", 14 * -1)
    )

    image_path1 = relative_to_assets("image_1.png")
    og_image1 = Image.open(image_path1)
    og_image1 = og_image1.resize((713, 446))
    image_image1 = ImageTk.PhotoImage(og_image1)

    canvas.place(x = 0, y = 0)
    image_1 = canvas.create_image(
        713 / 2,
        446 / 2,
        image=image_image1
    )

    canvas.create_rectangle(
        188.0,
        2.0,
        526.0,
        448.0,
        fill="#B8D1E8",
        outline="")

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_1 clicked"),
        relief="flat"
    )
    button_1.place(
        x=251.0,
        y=369.0,
        width=202.0,
        height=34.0
    )

    canvas.create_text(
        232.0,
        318.0,
        anchor="nw",
        text="Forgot Password? Click to reset",
        fill="#000000",
        font=("IstokWeb Regular", 16 * -1)
    )
    login_info = {
        "admin": "adminpassword23",
        "user1": "user1password"
    }
    # using this file as a reference for login info

    button_image_2 = PhotoImage(
        file=relative_to_assets("button_2.png"))
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: handle_login(),
        relief="flat"
    )
    button_2.place(
        x=251.0,
        y=256.0,
        width=202.0,
        height=34.0
    )

    entry_image_1 = PhotoImage(
        file=relative_to_assets("entry_1.png"))
    entry_bg_1 = canvas.create_image(
        352.0,
        219.0,
        image=entry_image_1
    )
    entry_1 = Entry(
        bd=0,
        bg="#E5F5FF",
        fg="#000716",
        highlightthickness=0
    )
    entry_1.place(
        x=251.0,
        y=202.0,
        width=202.0,
        height=32.0
    )

    canvas.create_text(
        251.0,
        179.0,
        anchor="nw",
        text="Password",
        fill="#000000",
        font=("IstokWeb Regular", 16 * -1)
    )

    entry_image_2 = PhotoImage(
        file=relative_to_assets("entry_2.png"))
    entry_bg_2 = canvas.create_image(
        352.0,
        155.0,
        image=entry_image_2
    )
    entry_2 = Entry(
        bd=0,
        bg="#E4F4FF",
        fg="#000716",
        highlightthickness=0
    )
    entry_2.place(
        x=251.0,
        y=138.0,
        width=202.0,
        height=32.0
    )

    canvas.create_text(
        251.0,
        115.0,
        anchor="nw",
        text="Username",
        fill="#000000",
        font=("IstokWeb Regular", 16 * -1)
    )

    canvas.create_text(
        327.0,
        53.0,
        anchor="nw",
        text="Login",
        fill="#000000",
        font=("IstokWeb Regular", 24 * -1)
    )

    canvas.create_text(
        265.0,
        88.0,
        anchor="nw",
        text="Sign In To Your Account",
        fill="#5A5050",
        font=("IstokWeb Regular", 16 * -1)
    )
    def check_login(username, password):
        if username in login_info and login_info[username] == password:
            return True
        else:
            return False
    def handle_login():
        username = entry_2.get()
        password = entry_1.get()
        if check_login(username, password):
            print("Login successful")
            window.destroy()
            open_dashboard_page()
            #canvas.itemconfig(status_label, text="Login successful", fill="green")
            return True
        # Optionally route to dashboard here
        else:
            print("Invalid username or password")
            #canvas.itemconfig(status_label, text="Invalid username or password", fill="red")

    window.resizable(False, False)
    window.mainloop()
