
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage



def open_register_page():
    def check_register(data):
        if data["username"] in data:
            return False
        else:
            return True
    def handle_register(data):
        username = entry_3.get()
        password = entry_2.get()
        re_password = entry_1.get()

        if check_register(data):
            if password == re_password:
                data[username] = password
                print("Registration successful")
                # Here you can add code to save the data to a file or database
            else:
                print("Passwords do not match")
        else:
            print("Username already exists")

    OUTPUT_PATH = Path(__file__).parent
    ASSETS_PATH = OUTPUT_PATH / Path(r"gui/assets/frame0Register").resolve()


    def relative_to_assets(path: str) -> Path:
        return ASSETS_PATH / Path(path)


    window = Tk()

    window.geometry("713x446")
    window.configure(bg = "#FFFFFF")


    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 446,
        width = 713,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        444.0,
        255.0,
        image=image_image_1
    )

    canvas.create_rectangle(
        188.0,
        2.0,
        526.0,
        448.0,
        fill="#B8D1E8",
        outline="")

    canvas.create_text(
        251.0,
        251.0,
        anchor="nw",
        text="Re-enter Password",
        fill="#000000",
        font=("IstokWeb Regular", 16 * -1)
    )

    entry_image_1 = PhotoImage(
        file=relative_to_assets("entry_1.png"))
    entry_bg_1 = canvas.create_image(
        352.0,
        294.0,
        image=entry_image_1
    )
    entry_1 = Entry(
        bd=0,
        bg="#E5F5FF",
        fg="#000716",
        highlightthickness=0
    )
    entry_1.place(
        x=251.0,
        y=277.0,
        width=202.0,
        height=32.0
    )
    from gui.LoginPage import open_login_page
    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: (window.destroy(), open_login_page()),
        relief="flat"
    )
    button_1.place(
        x=251.0,
        y=391.0,
        width=202.0,
        height=53.0
    )

    button_image_2 = PhotoImage(
        file=relative_to_assets("button_2.png"))
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_2 clicked"),
        relief="flat"
    )
    button_2.place(
        x=251.0,
        y=334.0,
        width=202.0,
        height=34.0
    )

    entry_image_2 = PhotoImage(
        file=relative_to_assets("entry_2.png"))
    entry_bg_2 = canvas.create_image(
        352.0,
        219.0,
        image=entry_image_2
    )
    entry_2 = Entry(
        bd=0,
        bg="#E5F5FF",
        fg="#000716",
        highlightthickness=0
    )
    entry_2.place(
        x=251.0,
        y=202.0,
        width=202.0,
        height=32.0
    )

    canvas.create_text(
        251.0,
        179.0,
        anchor="nw",
        text="Password",
        fill="#000000",
        font=("IstokWeb Regular", 16 * -1)
    )

    entry_image_3 = PhotoImage(
        file=relative_to_assets("entry_3.png"))
    entry_bg_3 = canvas.create_image(
        352.0,
        155.0,
        image=entry_image_3
    )
    entry_3 = Entry(
        bd=0,
        bg="#E4F4FF",
        fg="#000716",
        highlightthickness=0
    )
    entry_3.place(
        x=251.0,
        y=138.0,
        width=202.0,
        height=32.0
    )

    canvas.create_text(
        251.0,
        115.0,
        anchor="nw",
        text="Username",
        fill="#000000",
        font=("IstokWeb Regular", 16 * -1)
    )

    canvas.create_text(
        312.0,
        53.0,
        anchor="nw",
        text="Register",
        fill="#000000",
        font=("IstokWeb Regular", 24 * -1)
    )

    canvas.create_text(
        271.0,
        88.0,
        anchor="nw",
        text="Create A New Account",
        fill="#5A5050",
        font=("IstokWeb Regular", 16 * -1)
    )
    window.resizable(False, False)
    window.mainloop()
