
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from tkinter import messagebox

def open_welcome_page():
    OUTPUT_PATH = Path(__file__).parent
    ASSETS_PATH = OUTPUT_PATH / Path(r"gui/assets/frame0WelcomePage").resolve()


    def relative_to_assets(path: str) -> Path:
        return ASSETS_PATH / Path(path)


    window = Tk()

    window.geometry("713x446")
    window.configure(bg = "#FFFFFF")


    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 446,
        width = 713,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        444.0,
        255.0,
        image=image_image_1
    )
    from gui.LoginPage import open_login_page
    canvas.create_rectangle(
        0.0,
        1.0,
        713.0,
        447.0,
        fill="#B8D1E8",
        outline="")

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: (window.destroy(), open_login_page()),
        relief="flat"
    )
    button_1.place(
        x=366.0,
        y=234.0,
        width=202.0,
        height=34.0
    )
    from gui.RegisterPage import open_register_page
    button_image_2 = PhotoImage(
        file=relative_to_assets("button_2.png"))
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: (window.destroy(), open_register_page()),
        relief="flat"
    )
    button_2.place(
        x=366.0,
        y=296.0,
        width=202.0,
        height=34.0
    )

    canvas.create_text(
        62.0,
        62.0,
        anchor="nw",
        text="AI-Powered Intrusion Detection System",
        fill="#000000",
        font=("IstokWeb Regular", 28 * -1)
    )

    image_image_2 = PhotoImage(
        file=relative_to_assets("image_2.png"))
    image_2 = canvas.create_image(
        161.0,
        318.0,
        image=image_image_2
    )
    window.resizable(False, False)
    window.mainloop()
